### ISSUE TITLE
[INSTALLATION] Yarn build heap memory full

### ISSUE THREAD

**Issue by vincentbraillard** [texx00/sandypi#57]
**Describe the bug**
Fail to install firmware on raspberry pi 3b or 3b+ using node V 12.X.

**To Reproduce**
install node 12.x
Install sandypi

**Expected behavior**
fail to install. Fatal error
**Screenshots**

**Platform (please complete the following information):**
 - server hardware [Raspberry Pi 3B+,3B]

**Solution**
For raspberry Pi 3b or 3b+ you need to install node version 10.X following this link:
[https://noviello.it/come-installare-node-js-e-npm-su-raspberry-pi/](url)

**Comment by texx00** [comment]
Glad you found a solution... When I get the time I will check it out better to see if there is a way to run it on v12 or v14...

**Comment by texx00** [comment]
Closed by  #64

**Comment by texx00** [comment]
Closed by #64
