### ISSUE TITLE
HELP! Server Won't Start

### ISSUE THREAD

**Issue by tigert10** [texx00/sandypi#63]
Necessary details:
Raspbian
RPI4

Description of the problem:

I have tried a fresh install of SandyPi and it is getting hung up at the same spot. Seems to be a serial port problem but I'm at a loss as to how to fix. The install instructions talk about disregarding serial port warnings until you set the serial port in the GUI, but I can't get to the GUI as it won't initialize. It initializes until it gets to the device_serial.py

I have attached the feeder log. Hope it helps!
[feeder.log](https://github.com/texx00/sandypi/files/7592776/feeder.log)

**Comment by texx00** [comment]
Hi! You can try two things:
- did you set the autostart to be on? try to reboot the pi and use the "top" command to check if you have a flask service running already... If the service is running you should be able to connect directly without the need of starting it again even after a new installation
- try to delete (if you want make a backup copy before deleting it) the saved_settings.json file under server/saves (do not delete the default_settings.json) and run again the software

**Comment by tigert10** [comment]
Hi, tried both of your suggested solutions with no success.
I have identified that the problem is in the Frontend part of the install. 
Under the "Installing js dependencies and building frontend app" there seem to be many errors. But not sure how to solve them. I have included the install log file. Hope it helps. I look forward to your reply!
[install.log](https://github.com/texx00/sandypi/files/7597106/install.log)

**Comment by tigert10** [comment]
So in following your advice to another person with a similar issue here:
https://github.com/texx00/sandypi/issues/26
I tried doing the frontend yarn build trick and it gave an error. I have attached a txt file with the error. Hope it helps.
Thanks in advance for all your help!
[error.txt](https://github.com/texx00/sandypi/files/7597708/error.txt)

**Comment by texx00** [comment]
Looks like you are missing node-sass which is a library required during the installation. 
Not sure the reason why is not installed... Try to have a look at this if it works to fix the node-sass library. Otherwise you may need to build it or google some more about the installation on your version...
Hopefully problems like this will be fixed with #8 which is one of the priorities at the moment... Just need the time to set it up

**Comment by tigert10** [comment]
Got it! You were absolutely correct about the node-sass being the culprit. I think the problem stems from the node version that I was using. I could be wrong but I was using Node 17 and I don't think node-sass was compatible. After much troubleshooting I downgraded node to 12 and reinstalled SandyPi and behold it works. Thanks for your prompt replies and helpful responses. I really appreciate your work on this project! It is awesome!

**Comment by texx00** [comment]
Thanks! Since it is solved I will close it
