### ISSUE TITLE
Can't upload gcode files or create playlists

### ISSUE THREAD

**Issue by jkendric** [texx00/sandypi#75]
I am very sorry if this seem like more of a ""support" request than an issue per se.  I am sure I am doing something wrong.  I have been able to get the software up, running, and talking to my sandmachine on a Pi3 A+.  Unfortunately, any time I try to upload a gcode file, I get the error:

"There was a problem when uploading..."

Any suggestions would be appreciated.

**Comment by jkendric** [comment]
Thanks so much for the help.  It really seems to be a permissions issue and I am wondering if I don't have docker set up correctly.  When I try to navigate to the /var/lib/docker/volumes directory a get a Permissions Denied message.

I was able to get docker logs to give me the text that I pasted in the attached notepad document. I am also uploading the sample gcode I am using.
[log.txt](https://github.com/texx00/sandypi/files/8486504/log.txt)
[sandify_gcode.txt](https://github.com/texx00/sandypi/files/8486505/sandify_gcode.txt)

**Comment by texx00** [comment]
From the log I can see it is a bug... I fixed it in the development branch but I didn't push it to the main branch...
I'm pushing the fix right now... It will be available for download in a couple of hours I think....

You will need to use `docker-compose pull` to get the fresh image. Let me know if it fixes the problem

If you still think you have permission issues try to add the user to the docker group. Should be something like in this [guide](https://www.freecodecamp.org/news/the-easy-way-to-set-up-docker-on-a-raspberry-pi-7d24ced073ef/)

**Comment by jkendric** [comment]
Thank you!  That fixed the problem!  Playlists work, Files upload.  I am now getting problems with the gcode streaming, but it might be my hardware. Feel free to close this one out and I'll come back if I can't sort it out on my end.  Super cool software. I can't wait to use it!!!
